site_name: Splatoon Workspace
site_description: Splatoon scripts and layout documentation
site_url: https://exatrines.github.io/SplatoonWorkspace/
repo_url: https://github.com/exatrines/SplatoonWorkspace
repo_name: exatrines/SplatoonWorkspace
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode

plugins:
  - search

nav:
  - Home: index.md
  - ja:
      - Dawntrail:
          - EX3 極エターナルクイーン討滅線:
              - Scripts:
                  - EX3 端末射出: ja/Dawntrail/EX3/Scripts/EX3_Coronation.md
      - Endwalker:
          - 絶オメガ検証戦:
              - Scripts:
                  - P3 コロッサスブロー: ja/Endwalker/TOP/Scripts/P3_Transition.md
                  - P5 コード：＊＊＊ミ＊【シグマ】 塔マクロ押さない式ガイド: ja/Endwalker/TOP/Scripts/P5_Dynamis_Sigma_Relative_Tower_Finder.md
                  - P5 コード：＊＊＊ミ＊【シグマ】 ハロワ: ja/Endwalker/TOP/Scripts/P5_Dynamis_Sigma_Hello_World.md
                  - P5 コード：＊＊＊ミ＊【オメガ】 激せま安置ガイド: ja/Endwalker/TOP/Scripts/P5_Dynamis_Omega_Safe_Guide.md
                  - P5 コード：＊＊＊ミ＊【オメガ】 ハロワ: ja/Endwalker/TOP/Scripts/P5_Dynamis_Omega_Hello_World.md
  - en:
      - Dawntrail:
          - EX3 The Minstrel's Ballad: Sphene's Burden:
              - Scripts:
                  - EX3 Coronation: en/Dawntrail/EX3/Scripts/EX3_Coronation.md
      - Endwalker:
          - The Omega Protocol (Ultimate):
              - Scripts:
                  - P3 Transition: en/Endwalker/TOP/Scripts/P3_Transition.md
                  - P5 Dynamis Sigma Relative Tower Finder: en/Endwalker/TOP/Scripts/P5_Dynamis_Sigma_Relative_Tower_Finder.md
                  - P5 Dynamis Sigma Hello World: en/Endwalker/TOP/Scripts/P5_Dynamis_Sigma_Hello_World.md
                  - P5 Dynamis Omega Safe Guide: en/Endwalker/TOP/Scripts/P5_Dynamis_Omega_Safe_Guide.md
                  - P5 Dynamis Omega Hello World: en/Endwalker/TOP/Scripts/P5_Dynamis_Omega_Hello_World.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  generator: false
